[package]
changelog = "CHANGELOG.md"
versioned_files = [
    "packages/api-models-py/pyproject.toml",
    "packages/client-py/pyproject.toml",
    { path = "packages/client-py/pyproject.toml", regex = "skyportal-py-models==(?<version>\\d+\\.\\d+\\.\\d+)" },
    "packages/api-models-ts/package.json",
    "packages/client-ts/package.json",
]

[[workflows]]
name = "document-change"

[[workflows.steps]]
type = "CreateChangeFile"

[[workflows]]
name = "prepare-release"

[[workflows.steps]]
type = "Command"
command = "git switch --force-create release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: release $version\""

[[workflows.steps]]
type = "Command"
command = "git push --force --set-upstream origin release"

[[workflows.steps]]
type = "CreatePullRequest"
base = "main"

[workflows.steps.title]
template = "chore: release $version"

[workflows.steps.body]
template = "Merging this pull request releases every package at $version to PyPI and npm.\n\n$changelog"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "Release"

[github]
owner = "leonitousconforti"
repo = "skyportal-monorepo"
