[project]
name = "skyportal-monorepo"
version = "0"
requires-python = ">=3.11"
dependencies = ["skyportal-py", "skyportal-py-models"]

[dependency-groups]
dev = ["ruff", "ty"]
test = ["pytest", "respx"]

[tool.uv]
package = false
default-groups = ["dev", "test"]
workspace = { members = ["packages/api-models-py", "packages/client-py"] }

[tool.uv.sources]
skyportal-py = { workspace = true }
skyportal-py-models = { workspace = true }

[tool.ty.environment]
root = ["packages/api-models-py", "packages/client-py"]

[tool.ty.src]
include = ["packages/api-models-py", "packages/client-py"]
